### ISSUE TITLE
Cannot find module '../../core/server/errors'

### ISSUE THREAD

**Issue by azurewraith** [thombuchi/ghost-google-cloud-storage#3]
Received an error after adding this package on ghost 0.11.3...

    Unhandled rejection Error
    at Error.IncorrectUsage (/app/node_modules/ghost/core/server/errors/incorrect-usage.js:3:18)
    at Object.getStorage (/app/node_modules/ghost/core/server/storage/index.js:36:19)
    at setupMiddleware (/app/node_modules/ghost/core/server/middleware/index.js:126:44)
    at /app/node_modules/ghost/core/server/index.js:188:9

which was masking...

    Unhandled rejection Error: Cannot find module '../../core/server/errors'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/app/node_modules/ghost-google-cloud-storage/index.js:8:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/app/content/storage/gcloud/index.js:2:18)

    errors      = require('../../core/server/errors'),
    utils       = require('../../core/server/utils'),
    baseStore   = require('../../core/server/storage/base'),

after I changed these lines to:

    errors      = require('../ghost/core/server/errors'),
    utils       = require('../ghost/core/server/utils'),
    baseStore   = require('../ghost/core/server/storage/base'),

everything started working fine... I have my installation installed as part of a manifest for "ghost-on-heroku" which is probably why the dynamic pathing fails...

**Comment by devx** [comment]
I'm running `ghost` version `1.20.3`, and I don't have any of the errors you mentioned.
